name: License Self Verification

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  license_verification:
    runs-on: ${{ matrix.os }}

    outputs:
      ubuntu-latest_md: ${{ steps.self_verification.outputs.ubuntu-latest_md }}
      ubuntu-latest_warn_cnt: ${{ steps.self_verification.outputs.ubuntu-latest_warn_cnt }}
      ubuntu-latest_denied_cnt: ${{ steps.self_verification.outputs.ubuntu-latest_denied_cnt }}
      windows-latest_md: ${{ steps.self_verification.outputs.windows-latest_md }}
      windows-latest_warn_cnt: ${{ steps.self_verification.outputs.windows-latest_warn_cnt }}
      windows-latest_denied_cnt: ${{ steps.self_verification.outputs.windows-latest_denied_cnt }}
      macos-latest_md: ${{ steps.self_verification.outputs.macos-latest_md }}
      macos-latest_warn_cnt: ${{ steps.self_verification.outputs.macos-latest_warn_cnt }}
      macos-latest_denied_cnt: ${{ steps.self_verification.outputs.macos-latest_denied_cnt }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npx license-checker --unknown --json --out license_list.json
      - id: self_verification
        shell: bash
        run: |
          npx ts-node infra/license/license_self_verify.ts license_list.json ${{ matrix.os }}

          RESULT=$(cat ${{ matrix.os }}.md)
          RESULT="${RESULT//$'\n'/$'%0A'}"
          RESULT="${RESULT//$'\r'/$'%0D'}"

          WARN_CNT=$(cat ${{ matrix.os }}.warning.cnt)
          DENIED_CNT=$(cat ${{ matrix.os }}.denied.cnt)

          echo "::set-output name=${{ matrix.os }}_md::$RESULT"
          echo "::set-output name=${{ matrix.os }}_warn_cnt::$WARN_CNT"
          echo "::set-output name=${{ matrix.os }}_denied_cnt::$DENIED_CNT"
  
  report_verification_result:
    runs-on: ubuntu-latest

    needs: [ license_verification ]

    steps:
      - id: result_integration
        run: |
          WARN_COUNT=$((${{ needs.license_verification.outputs.ubuntu-latest_warn_cnt }} + \
            ${{ needs.license_verification.outputs.windows-latest_warn_cnt }} + \
            ${{ needs.license_verification.outputs.macos-latest_warn_cnt }}))
          DENIED_COUNT=$((${{ needs.license_verification.outputs.ubuntu-latest_denied_cnt }} + \
            ${{ needs.license_verification.outputs.windows-latest_denied_cnt }} + \
            ${{ needs.license_verification.outputs.macos-latest_denied_cnt }}))

          echo "### License Self Verification (DRAFT / NOT OFFICIAL)" > result
          echo "" >> result
          if [ "$WARN_COUNT" -ne "0" ] || ["$DENIED_COUNT" -ne "0" ]; then
            echo ":warning: Total ${WARN_COUNT} Warnings Found" >> result
            echo ":no_entry: Total ${DENIED_COUNT} Denials Found" >> result
          else
            echo ":heavy_check_mark: No License Issues Found" >> result
          fi
          echo "<details><summary>Detailed Result</summary>" >> result
          echo "" >> result
          echo "${{ needs.license_verification.outputs.ubuntu-latest_md }}" >> result
          echo "" >> result
          echo "---" >> result
          echo "" >> result
          echo "${{ needs.license_verification.outputs.windows-latest_md }}" >> result
          echo "" >> result
          echo "---" >> result
          echo "" >> result
          echo "${{ needs.license_verification.outputs.macos-latest_md }}" >> result
          echo "</details>" >> result

          RESULT=$(cat result)
          RESULT="${RESULT//$'\n'/$'%0A'}"
          RESULT="${RESULT//$'\r'/$'%0D'}"
          echo "::set-output name=body::$RESULT"

      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${{ steps.result_integration.outputs.body }}`
            })
